-- Playime — SQLite schema (v1, Phase 1)
-- Tables: session, message
--
-- Conventions:
--   - TEXT PKs are UUIDs generated by the app (crypto.randomUUID()).
--   - created_at / timestamps are integer ms epoch.
--   - Boolean flags are INTEGER 0/1 (SQLite has no bool type).
--   - message.seq is a per-session monotonic order; ordering by
--     (session_id, seq) is stable even if created_at collides.
--   - Connection-level PRAGMAs (foreign_keys, journal_mode) are applied by
--     the client (src/db.ts), not stored here.

CREATE TABLE IF NOT EXISTS session (
  id          TEXT PRIMARY KEY,                       -- uuid
  class       TEXT NOT NULL DEFAULT 'character'
              CHECK (class IN ('character', 'story')),
  created_at  INTEGER NOT NULL,                       -- ms epoch
  provider    TEXT NOT NULL DEFAULT 'opencode',       -- LM provider id
  model       TEXT,                                   -- main model id (nullable until resolved)
  small_model TEXT                                    -- bookkeeping model (summarize / state extraction)
);

CREATE TABLE IF NOT EXISTS message (
  id          TEXT PRIMARY KEY,                       -- uuid
  session_id  TEXT NOT NULL REFERENCES session(id) ON DELETE CASCADE,
  seq         INTEGER NOT NULL,                       -- per-session monotonic order
  role        TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content     TEXT NOT NULL,
  created_at  INTEGER NOT NULL,                       -- ms epoch
  visible     INTEGER NOT NULL DEFAULT 1,             -- 0 hides bookkeeping turns from the UI
  ooc         INTEGER NOT NULL DEFAULT 0,             -- 1 = out-of-character aside (excluded from fiction context)
  UNIQUE (session_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_message_session_seq ON message (session_id, seq);
