-- Playime — SQLite schema (v4, Phase 2.5 — avatars + starting scenarios + default_persona)
-- Tables: session, message, character_card, persona, id_sequences, session_event
--
-- Schema versioning: bump this comment when modifying the schema. The
-- runMigrations() function in src/db.ts handles ALTERs for existing DBs;
-- once all production DBs have a column, its migration can be removed and
-- this comment bumped. Current version: v4.
--
-- Conventions:
--   - TEXT PKs are UUIDs generated by the app (crypto.randomUUID()).
--   - created_at / timestamps are integer ms epoch.
--   - Boolean flags are INTEGER 0/1 (SQLite has no bool type).
--   - message.seq is a per-session monotonic order; ordering by
--     (session_id, seq) is stable even if created_at collides.
--   - Structured JSON fields (relationship_state, tags, world_info, ...)
--     are stored as TEXT and parsed by the app layer, not by SQLite.
--   - Connection-level PRAGMAs (foreign_keys, journal_mode) are applied by
--     the client (src/db.ts), not stored here.

-- ──────────────────────────────────────────────────────────────────────
-- Core tables (Phase 1)
-- ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS session (
  id          TEXT PRIMARY KEY,                       -- uuid
  class       TEXT NOT NULL DEFAULT 'character'
              CHECK (class IN ('character', 'story')),
  created_at  INTEGER NOT NULL,                       -- ms epoch
  provider    TEXT NOT NULL DEFAULT 'opencode',       -- LM provider id
  model       TEXT,                                   -- main model id (nullable until resolved)
  small_model TEXT,                                   -- bookkeeping model (summarize / state extraction)
  character_card_id TEXT REFERENCES character_card(id), -- which card this session plays (nullable until linked)
  avatar_selection TEXT,                               -- which avatar the user picked at New Play
  starting_scenario_id TEXT,                           -- which starting scenario the user picked at New Play
  avatar_snapshot TEXT,                                -- JSON snapshot of the selected AvatarOption
  starting_scenario_snapshot TEXT,                     -- JSON snapshot of the selected StartingScenario
  persona_id TEXT,                                    -- which persona (user identity) the user picked
  persona_snapshot TEXT,                              -- JSON snapshot of the selected Persona
  persona_source TEXT,                                -- "default" (from scenario) or "custom" (from library)
  favorite INTEGER NOT NULL DEFAULT 0                 -- 1 = user has marked this session as favorite
);

CREATE TABLE IF NOT EXISTS message (
  id          TEXT PRIMARY KEY,                       -- uuid
  session_id  TEXT NOT NULL REFERENCES session(id) ON DELETE CASCADE,
  seq         INTEGER NOT NULL,                       -- per-session monotonic order
  role        TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content     TEXT NOT NULL,
  created_at  INTEGER NOT NULL,                       -- ms epoch
  visible     INTEGER NOT NULL DEFAULT 1,             -- 0 hides bookkeeping turns from the UI
  ooc         INTEGER NOT NULL DEFAULT 0,             -- 1 = out-of-character aside (excluded from fiction context)
  UNIQUE (session_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_message_session_seq ON message (session_id, seq);

-- ──────────────────────────────────────────────────────────────────────
-- Character cards (Phase 2 foundation)
-- ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS character_card (
  id              TEXT PRIMARY KEY,                   -- uuid

  -- Core persona
  name            TEXT NOT NULL,
  avatar          TEXT,                               -- default avatar URL or base64 data URI (legacy)
  avatar_file     TEXT,                               -- local filename (e.g. "avatar.png")
  tagline         TEXT NOT NULL DEFAULT '',
  personality     TEXT NOT NULL DEFAULT '',
  speech_style    TEXT NOT NULL DEFAULT '',
  likes_and_dislikes TEXT NOT NULL DEFAULT '',
  scenario        TEXT NOT NULL DEFAULT '',            -- legacy single scenario (kept for backward compat)
  first_message   TEXT,                               -- legacy opening line (kept for backward compat)

  -- Relationship starting state (JSON: {affection, trust, flags})
  relationship_state TEXT NOT NULL DEFAULT '{"affection":0,"trust":0,"flags":[]}',

  -- Prompt tuning
  length_guidance TEXT,                               -- per-card response length hint

  -- Multiple avatars and starting scenarios
  avatars         TEXT NOT NULL DEFAULT '[]',         -- JSON array of AvatarOption
  starting_scenarios TEXT NOT NULL DEFAULT '[]',      -- JSON array of StartingScenario
  default_persona TEXT,                               -- JSON DefaultPersona (card-level, not per-scenario)

  -- Tavern V2/V3 card-spec compatibility fields
  -- (populated on import, editable in the creation form, never silently dropped)
  alternate_greetings TEXT NOT NULL DEFAULT '[]',     -- JSON array of strings
  mes_example     TEXT,                               -- example dialogue
  system_prompt   TEXT,                               -- card-level system prompt override
  post_history_instructions TEXT,                     -- injected after history, before the reply
  creator         TEXT,
  creator_notes   TEXT,
  character_version TEXT,
  world_info      TEXT NOT NULL DEFAULT '[]',         -- JSON array of WorldInfoEntry (Phase 2.5)
  extensions      TEXT NOT NULL DEFAULT '{}',         -- passthrough for unmapped V2/V3 fields

  -- Card-browser metadata (shared shape with future StoryCard)
  cover_image     TEXT,
  cover_file      TEXT,                               -- local filename for cover
  creator_name    TEXT,
  tags            TEXT NOT NULL DEFAULT '[]',         -- JSON array of strings
  description     TEXT,                               -- short one-line description
  prologue_preview TEXT,                              -- excerpt shown before starting
  stats           TEXT NOT NULL DEFAULT '{"replay_count":0,"like_count":0,"comment_count":0}',

  -- Import provenance
  source          TEXT NOT NULL DEFAULT 'playime',    -- original origin: 'playime' | 'chub' | 'sillytavern' | 'unknown'
  source_id       TEXT,                               -- original external ID (null if created in Playime)

  -- Timestamps
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL,

  -- User preferences
  favorite        INTEGER NOT NULL DEFAULT 0          -- 1 = user has marked this card as favorite
);

-- ──────────────────────────────────────────────────────────────────────
-- Key-event timeline (per-session, NOT on the card)
-- ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS session_event (
  id              TEXT PRIMARY KEY,                   -- uuid
  session_id      TEXT NOT NULL REFERENCES session(id) ON DELETE CASCADE,
  timestamp_start INTEGER,                            -- optional range start (ms epoch)
  timestamp_end   INTEGER,                            -- optional range end (ms epoch)
  entries         TEXT NOT NULL DEFAULT '[]',          -- JSON array of strings
  sort_order      INTEGER NOT NULL                    -- chronological ordering within the session
);

CREATE INDEX IF NOT EXISTS idx_session_event_session ON session_event (session_id, sort_order);

-- ──────────────────────────────────────────────────────────────────────
-- User Personas (who the user is playing as)
-- ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS persona (
  id              TEXT PRIMARY KEY,                   -- uuid
  name            TEXT NOT NULL,
  avatar          TEXT,                               -- user's profile image (URL or data URI)
  avatar_file     TEXT,                               -- local filename (e.g. "avatar.png")
  description     TEXT NOT NULL DEFAULT '',            -- short role description, e.g. "Apprentice Mage"
  appearance      TEXT NOT NULL DEFAULT '',            -- physical appearance for prompt context
  personality     TEXT NOT NULL DEFAULT '',            -- personality traits for prompt context
  pronouns        TEXT NOT NULL DEFAULT '',            -- e.g. "she/her"
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

-- ──────────────────────────────────────────────────────────────────────
-- Structured ID sequence counters
-- ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS id_sequences (
  type      TEXT NOT NULL,    -- 'char', 'story', 'persona', 'sess', 'msg'
  slug      TEXT NOT NULL,    -- slug for named entities, '' for sessions/messages
  next_seq  INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (type, slug)
);
